[package]
name = "netter_core"
version = "0.1.0"
edition = "2024"
description = "Core for Netter project"
license = "MIT"
repository = "https://github.com/bjfssd757/Netter"

[dependencies]
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
