[package]
name = "netter"
version = "0.2.1"
edition = "2024"
description = "Netter is a CLI tool for fast and easy server startup!"
license = "MIT"
reepository = "https://github.com/bjfssd757/Netter"

[dependencies]
clap = { version="4.5.35", features=["derive"] }
diesel = { version = "2.2.9", features = ["postgres"] }
dotenvy = "0.15.7"
flexi_logger = "0.30.1"
futures-util = "0.3.31"
http-body-util = "0.1.3"
hyper = { version="1.6.0", features=["full"] }
hyper-util = { version="0.1.11", features=["full"] }
lazy_static = "1.5.0"
log = "0.4.27"
pest = "2.8.0"
pest_derive = "2.8.0"
serde = { version="1.0.219", features=["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
tokio = { version="1.44.2", features=["full"] }
tokio-tungstenite = "0.26.2"
toml = "0.8.20"
