[package]
name = "netter_advanced_plugins"
version = "0.1.0"
edition = "2024"

[dependencies]
netter_plugger = "0.1.1"
lazy_static = "1.5.0"
serde_json = "1.0.140"
ctor = "0.4.2"
rand = "0.9.2"

[lib]
name = "plugin_name"
crate-type = ["cdylib"]