name: Build cli

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: build cli linux

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt update
        sudo apt install postgresql postgresql-contrib libpq-dev

    - name: Build
      run: cargo build --release -v

  build-windows:
    name: build cli windows

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install PgSQL
      run: |
        choco install postgresql --version=16 --params '/Password:postgres' -y
        setx PATH "%PATH%;C:\Program Files\PostgreSQL\16\bin"
    - name: Build CLI
      run: cargo build --release -v
        

  test:
    name: test cli

    needs: [build-linux, build-windows]

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout/@v4
      - name: Test
        run: cargo test -v
    
